language: node_js
node_js:
  - 9
script:
  - yarn storybook:build
  - yarn docz:build
  - yarn build

cache:
  yarn: true
deploy:
  - provider: pages
    skip-cleanup: true
    local-dir: docs
    github-token: $GITHUB_TOKEN
    keep-history: false
    on:
      branch: master
  - provider: npm
    skip-cleanup: true
    email: "renanccastro@gmail.com"
    api_key: $NPM_API_KEY
    on:
      tags: true
